
function GetTarotCardInformation(){
var tarotInformation = 
[
	{
		Name:'愚人',
		Number:'Big-00.The Fool',
		element:'風',
		InformationKeyY:'真誠、探索心、愛冒險、充滿希望',
		InformationKeyS:'擔憂、害怕、故步自封、退縮'
	},
	{
		Name:'魔術師',
		Number:'Big-01.The Magician',
		element:'風',
		InformationKeyY:'聰明靈活、擅長溝通、天資聰穎、展現自我',
		InformationKeyS:'情緒不穩、江湖騙子、焦慮、失去控制'
	},
	{
		Name:'女祭司',
		Number:'Big-02.The High Priestess',
		element:'水',
		InformationKeyY:'陰柔、直覺強烈、情感內斂、冷靜',
		InformationKeyS:'大膽、熱情、展現自我、喜歡交際'
	},
	{
		Name:'女皇',
		Number:'Big-03.The Emepress',
		element:'土',
		InformationKeyY:'豐盛、溫柔、懷孕、穩定、愛情',
		InformationKeyS:'浪費、貪婪、不誠實、爛桃花'
	},
	{
		Name:'皇帝',
		Number:'Big-04.The Emperor',
		element:'火',
		InformationKeyY:'積極、驕傲、指揮、目中無人',
		InformationKeyS:'缺乏同理、攻擊、傷害、殘暴'
	},
	{
		Name:'教皇',
		Number:'Big-05.The Hierophant',
		element:'土',
		InformationKeyY:'導師、分享、指引方向、舊有思維',
		InformationKeyS:'突破現狀、缺乏耐性、離開、進修'
	},
	{
		Name:'戀人',
		Number:'Big-06.The Lovers',
		element:'風',
		InformationKeyY:'合作夥伴、戀愛、幸福、成長',
		InformationKeyS:'分手、不合、不愉快'
	},
	{
		Name:'戰車',
		Number:'Big-07.The Chariot',
		element:'水',
		InformationKeyY:'行動、保護、堅定、發展',
		InformationKeyS:'卡住、意外、突發狀況、腹背受敵'
	},
	{
		Name:'力量',
		Number:'Big-08.Strength',
		element:'火',
		InformationKeyY:'有勇氣、不屈不饒、細心、有耐心',
		InformationKeyS:'暴躁、鬥爭、易怒、失去耐心'
	},
	{
		Name:'隱士',
		Number:'Big-09.The Hermit',
		element:'土',
		InformationKeyY:'自省、目標明確、找到方向、理性',
		InformationKeyS:'迷茫、停滯、失去方向'
	},
	{
		Name:'命運之輪',
		Number:'Big-10.Wheel of Fortune',
		element:'火',
		InformationKeyY:'希望、發展、升遷、機會',
		InformationKeyS:'停滯、困難、無動於衷'
	},
	{
		Name:'正義',
		Number:'Big-11.The Justice',
		element:'風',
		InformationKeyY:'公平、公正、均衡、穩固',
		InformationKeyS:'不公正、拒絕互動、官司纏繞'
	},
	{
		Name:'吊人',
		Number:'Big-12.The Hanged Man',
		element:'水',
		InformationKeyY:'堅持、耐心、犧牲奉獻、作繭自縛',
		InformationKeyS:'掙脫、不堅持、不等待、重新調整'
	},
	{
		Name:'死神',
		Number:'Big-13.The Death',
		element:'水',
		InformationKeyY:'過渡期、重生、順其自然、轉機',
		InformationKeyS:'失望、掙扎、不自信、停止'
	},
	{
		Name:'節制',
		Number:'Big-14.Temperance',
		element:'火',
		InformationKeyY:'耐心溝通、智慧、互動',
		InformationKeyS:'粗心、不理性、缺乏溝通、停止交流'
	},
	{
		Name:'惡魔',
		Number:'Big-15.The Devil',
		element:'土',
		InformationKeyY:'緣分、慾望、利益關係、沉默成本、前任',
		InformationKeyS:'糾纏、分手、分分合合、破局'
	},
	{
		Name:'高塔',
		Number:'Big-16.The Tower',
		element:'火',
		InformationKeyY:'意外狀況、崩塌、傷害',
		InformationKeyS:'自我衝突、暗中破壞'
	},
	{
		Name:'星星',
		Number:'Big-17.The Star',
		element:'風',
		InformationKeyY:'內在智慧、付出、方向正確、心想事成',
		InformationKeyS:'失望、事與願違、心靈匱乏'
	},
	{
		Name:'月亮',
		Number:'Big-18.The Moon',
		element:'水',
		InformationKeyY:'阻礙、幻覺、迷茫',
		InformationKeyS:'發現、阻礙減少、嘗試探索'
	},
	{
		Name:'太陽',
		Number:'Big-19.The Sun',
		element:'火',
		InformationKeyY:'動力、步步高升、重見光明',
		InformationKeyS:'臨門一腳、發展停頓、缺乏動力'
	},
	{
		Name:'審判',
		Number:'Big-20.Judgement',
		element:'水',
		InformationKeyY:'復甦、重生、轉機、貴人',
		InformationKeyS:'沒有希望、等待救援、時機未到'
	},
	{
		Name:'世界',
		Number:'Big-21.The World',
		element:'土',
		InformationKeyY:'圓滿、成功、巔峰、好結果',
		InformationKeyS:'受困、遺憾、臨門一腳'
	},
	/*----------權杖 Wands-------------*/
	{
		Name:'權杖一',
		Number:'Wands-01',
		element:'火',
		InformationKeyY:'開始、起點、行動力',
		InformationKeyS:'缺乏動力、停滯、消極'
	},
	{
		Name:'權杖二',
		Number:'Wands-02',
		element:'火',
		InformationKeyY:'初始計畫、找到方向、目標明確',
		InformationKeyS:'沒有目標、遠距離、計畫困難'
	},
	{
		Name:'權杖三',
		Number:'Wands-03',
		element:'火',
		InformationKeyY:'進展順利、好消息',
		InformationKeyS:'距離感、出行不順、不好的消息'
	},
	{
		Name:'權杖四',
		Number:'Wands-04',
		element:'火',
		InformationKeyY:'穩定、發展順利、合作愉快',
		InformationKeyS:'分裂、發展失利、合作失衡'
	},
	{
		Name:'權杖五',
		Number:'Wands-05',
		element:'火',
		InformationKeyY:'爭鬥、不愉快、不穩',
		InformationKeyS:'消極、不願繼續'
	},
	{
		Name:'權杖六',
		Number:'Wands-06',
		element:'火',
		InformationKeyY:'出擊、凝聚力',
		InformationKeyS:'不團結、失去人心'
	},
	{
		Name:'權杖七',
		Number:'Wands-07',
		element:'火',
		InformationKeyY:'抵抗、頂住壓力、不放棄希望',
		InformationKeyS:'放棄、消極'
	},
	{
		Name:'權杖八',
		Number:'Wands-08',
		element:'火',
		InformationKeyY:'快速發展',
		InformationKeyS:'行動受阻'
	},
	{
		Name:'權杖九',
		Number:'Wands-09',
		element:'火',
		InformationKeyY:'掌握一切、咬牙撐住',
		InformationKeyS:'失去力量、極度混亂'
	},
	{
		Name:'權杖十',
		Number:'Wands-10',
		element:'火',
		InformationKeyY:'喘不過氣、負責任、腳踏實地',
		InformationKeyS:'卸下重擔、不負責任、壓力舒緩'
	},
	{
		Name:'權杖騎士',
		Number:'Wands-Kinght',
		element:'火',
		InformationKeyY:'充滿熱忱、動力十足',
		InformationKeyS:'不積極、失去動力'
	},
	{
		Name:'權杖皇后',
		Number:'Wands-Queen',
		element:'火',
		InformationKeyY:'掌握一切、指引他人',
		InformationKeyS:'憤世忌俗、消極'
	},
	{
		Name:'權杖國王',
		Number:'Wands-King',
		element:'火',
		InformationKeyY:'掌握一切',
		InformationKeyS:'失去掌控、嘗試穩住陣腳'
	},
	{
		Name:'權杖侍者',
		Number:'Wands-Page',
		element:'火',
		InformationKeyY:'積極熱情、活潑',
		InformationKeyS:'不積極、內在衝突、焦躁'
	},
	/*-----------------聖杯 Cups-------------------*/
	{
		Name:'聖杯一',
		Number:'Cup-01',
		element:'水',
		InformationKeyY:'開始溝通、情感交流',
		InformationKeyS:'情感阻礙、溝通阻礙'
	},
	{
		Name:'聖杯二',
		Number:'Cup-02',
		element:'水',
		InformationKeyY:'美好合作、交流、平等相處',
		InformationKeyS:'拆夥、不愉悅合作'
	},
	{
		Name:'聖杯三',
		Number:'Cup-03',
		element:'水',
		InformationKeyY:'豐收、合作、第三者、社交場合',
		InformationKeyS:'拆夥、溝通不順'
	},
	{
		Name:'聖杯四',
		Number:'Cup-04',
		element:'水',
		InformationKeyY:'不切實際、想太多',
		InformationKeyS:'安於現狀、思考不周、收斂思緒'
	},
	{
		Name:'聖杯五',
		Number:'Cup-05',
		element:'水',
		InformationKeyY:'悲傷、困境、失望',
		InformationKeyS:'跨越困境、嘗試改善'
	},
	{
		Name:'聖杯六',
		Number:'Cup-06',
		element:'水',
		InformationKeyY:'被祝福、安全感',
		InformationKeyS:'不被祝福、不被理解'
	},
	{
		Name:'聖杯七',
		Number:'Cup-07',
		element:'水',
		InformationKeyY:'貴人運、選擇很多、舉棋不定',
		InformationKeyS:'缺乏機會、放棄選擇'
	},
	{
		Name:'聖杯八',
		Number:'Cup-08',
		element:'水',
		InformationKeyY:'想要離開、不滿現狀',
		InformationKeyS:'停留現狀、不敢追求'
	},
	{
		Name:'聖杯九',
		Number:'Cup-09',
		element:'水',
		InformationKeyY:'滿足現狀、分享他人',
		InformationKeyS:'不滿現狀、拒絕互動'
	},
	{
		Name:'聖杯十',
		Number:'Cup-10',
		element:'水',
		InformationKeyY:'感情順利、幸福喜悅',
		InformationKeyS:'失去信心、美中不足'
	},
	{
		Name:'聖杯侍者',
		Number:'Cup-Page',
		element:'水',
		InformationKeyY:'平等溝通、真誠坦露',
		InformationKeyS:'排斥他人、拒絕溝通'
	},
	{
		Name:'聖杯皇后',
		Number:'Cup-Queen',
		element:'水',
		InformationKeyY:'慈愛',
		InformationKeyS:'情緒不穩'
	},
	{
		Name:'聖杯國王',
		Number:'Cup-King',
		element:'水',
		InformationKeyY:'情感內斂、有智慧、安穩舒適',
		InformationKeyS:'負面情緒、暗潮洶湧'
	},
	{
		Name:'聖杯騎士',
		Number:'Cup-Kinght',
		element:'水',
		InformationKeyY:'消極等待、舒適圈',
		InformationKeyS:'思緒混亂'
	},
	/*-----------------寶劍 Cups-------------------*/
	{
		Name:'寶劍一',
		Number:'Swords-01',
		element:'風',
		InformationKeyY:'不穩定、新挑戰、虛幻',
		InformationKeyS:'展現自我、由虛轉實'
	},
	{
		Name:'寶劍二',
		Number:'Swords-02',
		element:'風',
		InformationKeyY:'不願面對',
		InformationKeyS:'願意敞開、慢慢面對'
	},
	{
		Name:'寶劍三',
		Number:'Swords-03',
		element:'風',
		InformationKeyY:'悲傷、失望',
		InformationKeyS:'備受打擊'
	},
	{
		Name:'寶劍四',
		Number:'Swords-04',
		element:'風',
		InformationKeyY:'休息',
		InformationKeyS:'掙脫、突破困局'
	},
	{
		Name:'寶劍五',
		Number:'Swords-05',
		element:'風',
		InformationKeyY:'暫時妥協',
		InformationKeyS:'衝突、不穩定'
	},
	{
		Name:'寶劍六',
		Number:'Swords-06',
		element:'風',
		InformationKeyY:'貴人相助、脫離困境、順其自然',
		InformationKeyS:'不穩定、缺乏貴人'
	},
	{
		Name:'寶劍七',
		Number:'Swords-07',
		element:'風',
		InformationKeyY:'偷偷摸摸、利用險招',
		InformationKeyS:'事跡敗露、坦坦蕩蕩'
	},
	{
		Name:'寶劍八',
		Number:'Swords-08',
		element:'風',
		InformationKeyY:'作繭自縛、受困過去',
		InformationKeyS:'放棄過去、脫離困境'
	},
	{
		Name:'寶劍九',
		Number:'Swords-09',
		element:'風',
		InformationKeyY:'擔憂、焦慮、內耗',
		InformationKeyS:'壓力減輕、不想放棄'
	},
	{
		Name:'寶劍十',
		Number:'Swords-10',
		element:'風',
		InformationKeyY:'結束',
		InformationKeyS:'不願面對、不想放棄'
	},
	{
		Name:'寶劍侍者',
		Number:'Swords-Page',
		element:'風',
		InformationKeyY:'排斥他人、壓力',
		InformationKeyS:'狀態穩定、稍微把握'
	},
	{
		Name:'寶劍皇后',
		Number:'Swords-Queen',
		element:'風',
		InformationKeyY:'嚴肅、不講情面',
		InformationKeyS:'事情不順'
	},
	{
		Name:'寶劍國王',
		Number:'Swords-King',
		element:'風',
		InformationKeyY:'高標準、過分理性',
		InformationKeyS:'不理性、稍微把握'
	},
	{
		Name:'寶劍騎士',
		Number:'Swords-Kinght',
		element:'風',
		InformationKeyY:'極端、強烈爭吵',
		InformationKeyS:'向現實低頭'
	},
	/*-----------------錢幣 Coins-------------------*/
	{
		Name:'錢幣一',
		Number:'Pentacles-01',
		element:'土',
		InformationKeyY:'穩定、沒有變化',
		InformationKeyS:'虛幻、變化不穩'
	},
	{
		Name:'錢幣二',
		Number:'Pentacles-02',
		element:'土',
		InformationKeyY:'選擇、努力平衡',
		InformationKeyS:'失去平衡、分化'
	},
	{
		Name:'錢幣三',
		Number:'Pentacles-03',
		element:'土',
		InformationKeyY:'合作、展現自己、互相學習',
		InformationKeyS:'學習長處、忽略細節'
	},
	{
		Name:'錢幣四',
		Number:'Pentacles-04',
		element:'土',
		InformationKeyY:'小氣、專注眼前、守護',
		InformationKeyS:'大方、不穩定、粗心'
	},
	{
		Name:'錢幣五',
		Number:'Pentacles-05',
		element:'土',
		InformationKeyY:'失去一切、艱苦困難',
		InformationKeyS:'不放棄希望、尋求協助'
	},
	{
		Name:'錢幣六',
		Number:'Pentacles-06',
		element:'土',
		InformationKeyY:'貴人運、不平等、合作',
		InformationKeyS:'失去幫助、不穩定'
	},
	{
		Name:'錢幣七',
		Number:'Pentacles-07',
		element:'土',
		InformationKeyY:'腳踏實地、持續付出、等待收成',
		InformationKeyS:'放棄、不願等待'
	},
	{
		Name:'錢幣八',
		Number:'Pentacles-08',
		element:'土',
		InformationKeyY:'耕耘、努力工作、方向正確',
		InformationKeyS:'散漫、不想付出'
	},
	{
		Name:'錢幣九',
		Number:'Pentacles-09',
		element:'土',
		InformationKeyY:'收成、承接機會',
		InformationKeyS:'尚未達標、不想努力'
	},
	{
		Name:'錢幣十',
		Number:'Pentacles-10',
		element:'土',
		InformationKeyY:'享受豐盛、安穩、成功',
		InformationKeyS:'不穩定、不滿意'
	},
	{
		Name:'錢幣侍者',
		Number:'Pentacles-Page',
		element:'土',
		InformationKeyY:'較踏實地、務實謹慎',
		InformationKeyS:'太保守'
	},
	{
		Name:'錢幣皇后',
		Number:'Pentacles-Queen',
		element:'土',
		InformationKeyY:'富足、享受現況',
		InformationKeyS:'不滿足'
	},
	{
		Name:'錢幣國王',
		Number:'Pentacles-King',
		element:'土',
		InformationKeyY:'穩若泰山、狀態安定',
		InformationKeyS:'阻礙重重'
	},
	{
		Name:'錢幣騎士',
		Number:'Pentacles-Kinght',
		element:'土',
		InformationKeyY:'按部就班',
		InformationKeyS:'遇到阻礙'
	}
]
return tarotInformation;
}